### ISSUE TITLE
Try to predict interesting repos when listing trending

### ISSUE THREAD

**Issue by hoop33** [hoop33/limo#56]
Opportunity to use fuzzy logic; based on current stars:
* Interesting languages
* Libraries vs programs
* CLI vs GUI
* OS (macOS, Windows, Linux)
* License
* Number of stars

**Comment by roscopecoltran** [comment]
Hi,

Hope u are all well !

Here are some additional suggestions for your limo project:

For more in depth results:
**1- Stargazers graph feature**
https://github.com/spencerkimball/stargazers
Maybe would require to use neo4j or graphql to see results.

here is a copy of my glide.yaml picking the right pkg version:
```
package: github.com/spencerkimball/stargazers
import:
- package: github.com/kennygrant/sanitize
  version: 7fdd72ab580907c39c5f0b8b98b8d89e5476f424
- package: golang.org/x/net
  version: e7b14352cc2ad797a09634fc0f1dd12942fa86de
- package: github.com/spf13/pflag
  version: 5ccb023bc27df288a957c5e994cd44fd19619465
- package: github.com/spf13/cobra
  version: 6e91dded25d73176bf7f60b40dd7aa1f0bf9be8d
- package: github.com/cockroachdb/cockroach
  version: 7bf1439e813747001a390d1e960669b3861a734f
```

**2- Small web-ui**
for web-ui, comparing to astral, I saw some ng-admin bindings with gin-gonic:
https://github.com/Onefootball/entity-rest-api

or maybe just to write a rest api compatible with astral front-end, would be more simple...

**3- Combine and compare most popular repos of 2016 and 2015** 
https://github.com/donnemartin/viz
I have a docker image ready for this one with python/tox but the data can be imported into a postgres/mysql or boltdb database. 

Cheers,
Richard
